### ISSUE TITLE
Getting error cannot access '*.raw': No such file or directory     while running run.sh 

### ISSUE THREAD

**Issue by query-box** [AaronJackson/vrn#84]
./run.sh 
Found Environment variable CUDNN_PATH = /usr/local/cuda-8.0/lib64/libcudnn.so.5.1.10Scanning directory for data...	
Found 5 images	
5 images require a face detector	
Initialising python libs...	
Initialising detector...	
Cropped and scaled AFLW_image00046.jpg
Cropped and scaled AFLW_image00095.jpg
Cropped and scaled AFLW_image00190.jpg
Cropped and scaled AFLW_image00656.jpg
Cropped and scaled asj.jpg
/home/mysystembox/torch/install/bin/luajit: /home/mysystembox/torch/install/share/lua/5.1/torch/File.lua:259: read error: read 0 blocks instead of 1 at /home/mysystembox/torch/pkg/torch/lib/TH/THDiskFile.c:352
stack traceback:
	[C]: in function 'readInt'
	/home/mysystembox/torch/install/share/lua/5.1/torch/File.lua:259: in function 'readObject'
	/home/mysystembox/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	process.lua:13: in main chunk
	[C]: in function 'dofile'
	...hinx/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
ls: cannot access '*.raw': No such file or directory

Cuda version: 8.0
Cudnn: 5.1.10

**Comment by AaronJackson** [comment]
I don't think you have downloaded the model correctly.

**Comment by query-box** [comment]
Thanks for your quick reply. I followed the instructions mentioned in readme file. Let me re-clone and redo the procedure.

**Comment by query-box** [comment]
The issue was that during running ./download.sh my system free memory was low, due to which the file size of vrn-unguided.t7 was 0bytes. Now after freeing some memory and reinstalling it with the described procedures present in readme( and edits discussed from issues) the code is running well. Thanks :) Earlier I was thinking there is some issue with torch or cuda :D

**Comment by AaronJackson** [comment]
Wondered if it was something like that. Very good :)
